O notebook deverá incluir:
- análise do conjunto de dados e sua breve descrição
- tarefas de pré-processamento dos dados (se julgar necessárias)
- sumarização dos dados (estatística descritiva, exploração com recurso
a gráficos)
- análise estatística multivariada (não supervisionada): clustering,
redução de dimensionalidade/ visualização
- análise preditiva/ aprendizagem máquina (classificação ou regressão
conforme apropriado), comparando o desempenho de vários modelos
- seleção/ importância das variáveis usadas pelos modelos

A apresentação dos resultados deverá incluir:
- apresentação do pipeline de análise e ferramentas usadas
- apresentação dos principais resultados obtidos
- discussão

In [ ]:
# Load packages
import pandas as p
import numpy as n

In [ ]:
# Import data
# ames_features -> atributos dos medicamentos
# ames_outputs -> contém string SMILES do medicamento e variável binária mutagénico (S/N)
feat = p.read_csv("ames_features.csv", sep=',')
out = p.read_csv("ames_outputs.csv", sep=',')

In [16]:
p.set_option('display.max_columns', None)
feat.head(10)

,MaxEStateIndex,MinEStateIndex,MaxAbsEStateIndex,MinAbsEStateIndex,qed,MolWt,HeavyAtomMolWt,ExactMolWt,NumValenceElectrons,NumRadicalElectrons,MaxPartialCharge,MinPartialCharge,MaxAbsPartialCharge,MinAbsPartialCharge,FpDensityMorgan1,FpDensityMorgan2,FpDensityMorgan3,BCUT2D_MWHI,BCUT2D_MWLOW,BCUT2D_CHGHI,BCUT2D_CHGLO,BCUT2D_LOGPHI,BCUT2D_LOGPLOW,BCUT2D_MRHI,BCUT2D_MRLOW,BalabanJ,BertzCT,Chi0,Chi0n,Chi0v,Chi1,Chi1n,Chi1v,Chi2n,Chi2v,Chi3n,Chi3v,Chi4n,Chi4v,HallKierAlpha,Ipc,Kappa1,Kappa2,Kappa3,LabuteASA,PEOE_VSA1,PEOE_VSA10,PEOE_VSA11,PEOE_VSA12,PEOE_VSA13,PEOE_VSA14,PEOE_VSA2,PEOE_VSA3,PEOE_VSA4,PEOE_VSA5,PEOE_VSA6,PEOE_VSA7,PEOE_VSA8,PEOE_VSA9,SMR_VSA1,SMR_VSA10,SMR_VSA2,SMR_VSA3,SMR_VSA4,SMR_VSA5,SMR_VSA6,SMR_VSA7,SMR_VSA8,SMR_VSA9,SlogP_VSA1,SlogP_VSA10,SlogP_VSA11,SlogP_VSA12,SlogP_VSA2,SlogP_VSA3,SlogP_VSA4,SlogP_VSA5,SlogP_VSA6,SlogP_VSA7,SlogP_VSA8,SlogP_VSA9,TPSA,EState_VSA1,EState_VSA10,EState_VSA11,EState_VSA2,EState_VSA3,EState_VSA4,EState_VSA5,EState_VSA6,EState_VSA7,EState_VSA8,EState_VSA9,VSA_EState1,VSA_EState10,VSA_EState2,VSA_EState3,VSA_EState4,VSA_EState5,VSA_EState6,VSA_EState7,VSA_EState8,VSA_EState9,FractionCSP3,HeavyAtomCount,NHOHCount,NOCount,NumAliphaticCarbocycles,NumAliphaticHeterocycles,NumAliphaticRings,NumAromaticCarbocycles,NumAromaticHeterocycles,NumAromaticRings,NumHAcceptors,NumHDonors,NumHeteroatoms,NumRotatableBonds,NumSaturatedCarbocycles,NumSaturatedHeterocycles,NumSaturatedRings,RingCount,MolLogP,MolMR,fr_Al_COO,fr_Al_OH,fr_Al_OH_noTert,fr_ArN,fr_Ar_COO,fr_Ar_N,fr_Ar_NH,fr_Ar_OH,fr_COO,fr_COO2,fr_C_O,fr_C_O_noCOO,fr_C_S,fr_HOCCN,fr_Imine,fr_NH0,fr_NH1,fr_NH2,fr_N_O,fr_Ndealkylation1,fr_Ndealkylation2,fr_Nhpyrrole,fr_SH,fr_aldehyde,fr_alkyl_carbamate,fr_alkyl_halide,fr_allylic_oxid,fr_amide,fr_amidine,fr_aniline,fr_aryl_methyl,fr_azide,fr_azo,fr_barbitur,fr_benzene,fr_benzodiazepine,fr_bicyclic,fr_diazo,fr_dihydropyridine,fr_epoxide,fr_ester,fr_ether,fr_furan,fr_guanido,fr_halogen,fr_hdrzine,fr_hdrzone,fr_imidazole,fr_imide,fr_isocyan,fr_isothiocyan,fr_ketone,fr_ketone_Topliss,fr_lactam,fr_lactone,fr_methoxy,fr_morpholine,fr_nitrile,fr_nitro,fr_nitro_arom,fr_nitro_arom_nonortho,fr_nitroso,fr_oxazole,fr_oxime,fr_para_hydroxylation,fr_phenol,fr_phenol_noOrthoHbond,fr_phos_acid,fr_phos_ester,fr_piperdine,fr_piperzine,fr_priamide,fr_prisulfonamd,fr_pyridine,fr_quatN,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,11.663401,-0.396099,11.663401,0.008895,0.181963,342.310,332.230,342.06406,124.0,0.0,0.277383,-0.258290,0.277383,0.258290,0.538462,0.923077,1.307692,16.631770,9.878024,2.243219,-2.142638,2.460575,-1.957799,6.364064,-0.382738,2.267149,1284.79020,17.999271,13.300923,13.300923,12.575387,7.986911,7.986911,6.240968,6.240968,4.982737,4.982737,3.980293,3.980293,-3.80,1.358228e+06,14.535237,4.857510,1.699174,145.443040,0.000000,0.000000,0.000000,0.00000,11.374773,0.000000,20.228636,0.000000,0.000000,0.000000,36.398200,33.677630,22.905182,20.619070,9.846622,54.464565,0.0,0.000000,0.000000,0.000000,0.000000,80.892300,0.0,0.0,0.000000,11.374773,0.0,0.00000,9.846622,0.000000,20.228636,0.000000,60.663670,0.0,43.089794,0.0,86.28,9.846622,20.228636,0.0,11.374773,32.317345,10.772449,12.132734,36.398200,12.132734,0.000000,0.000000,0.000000,0.000000,22.534605,28.751337,0.017789,0.000000,17.362938,0.000000,0.000000,0.0,0.000000,26.0,0.0,6.0,0.0,0.0,0.0,5.0,0.0,5.0,4.0,0.0,6.0,2.0,0.0,0.0,0.0,5.0,5.5536,100.9608,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,11.824743,-0.170602,11.824743,0.170602,0.269289,301.345,286.225,301.11030,112.0,0.0,0.280182,-0.258281,0.280182,0.258281,0.782609,1.434783,2.130435,16.628431,9.821377,2.272279,-2.209454,2.443384,-2.080122,6.253369,-0.383375,2.126255,1081.62600,15.551678,12.633589,12.633589,11.254020,8.111246,8.111246,6.450414,6.450414,5.293200,5.293200,4.366351,4.366351,-2.68,3.795956e+05,12.823625,4.415776,1.592870,132.562330,0.000000,0.000000,0.000000,0.00000,5.687386,0.000000,10.114318,0.000000,0.000000,0.000000,36.398200,58.858000,10.949676,10.309535,4.923311,38.004730,0.0,0.000000,0.000000,25.683287,0.000000,63.705790,0.0,0.0,0.000000,5.687386,0.0,0.00000,4.923311,12.841643,10.114318,23.968546,42.464570,0.0,32.317345,0.0,43.14,0.000000,10.114318,0.0,4.923311,5.687386,52.791634,16.335900,0.000000,18.199100,24.265469,0.000000,0.000000,0.000000,11.654141,18.396769,2.505822,0.000000,14.510819,3.932449,0.000000,0.0,0.200000,23.0,0.0,3.0,1.0,0.0,1.0,4.0,0.0,4.0,2.0,0.0,3.0,1.0,0.0,0.0,0.0,5.0,5.3710,93.4424,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,4.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,14.431072,-0.378575,14.431072,0.128988,0.184582,646.614,628.470,646.11650,232.0,0.0,0.196213,-0.353239,0.353239,0.196213,0.240000,0.520000,0.860000,16.143131,9.940472,2.259153,-2.054884,2.426829,-2.135155,6.392341,1.549090,1.489526,3545.35820,33.739030,25.687094,25.687094,24.346245,16.028162,16.028162,12.932863,12.932863,10.595806,10.595806,8.440805,8.440805,-7.06,7.842002e+11,26.949518,8.886481,2.983958,275.635500,9.967958,0.000000,32.572742,0.00000,0.000000,0.000000,28.767223,0.000000,0.000000,0.000000,84.929140,12.132734,64.634690,43.611700,0.000000,108.246390,0.0,9.967958,0.000000,0.000000,0.000000,158.401840,0.0,0.0,32.572742,0.000000,0.0,0.00000,9.967958,0.000000,0.000000,0.000000,125.829094,0.0,108.246390,0.0,134.00,0.000000,28.767223,0.0,86.434980,54.384148,0.000000,0.000000,97.061874,0.000000,9.967958,0.000000,0.000000,0.000000,91.118500,5.050742,-0.577214,0.000000,26.741308,0.000000,0.000000,0.0,0.000000,50.0,2.0,8.0,0.0,0.0,0.0,9.0,2.0,11.0,6.0,2.0,8.0,0.0,0.0,0.0,0.0,11.0,6.3494,201.3814,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,17.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,10.422196,-0.670278,10.422196,0.248657,0.103849,157.133,150.077,157.05997,60.0,0.0,0.344124,-0.361291,0.361291,0.344124,1.636364,2.272727,2.727273,16.158337,10.539093,2.026025,-1.959499,1.587213,-2.400163,6.237935,-0.123895,3.620019,206.52795,8.690234,5.572731,5.572731,5.201907,2.650904,2.650904,1.529888,1.529888,0.759153,0.759153,0.316506,0.316506,-1.72,2.347590e+02,9.280000,5.095621,4.763092,62.149140,10.847918,0.000000,0.000000,0.00000,5.907180,12.121780,15.014866,5.842670,4.789866,0.000000,0.000000,0.000000,0.000000,6.544756,14.378941,18.028960,0.0,10.742580,5.842670,0.000000,6.544756,5.531129,0.0,0.0,16.585250,0.000000,0.0,0.00000,29.363583,9.589074,0.000000,0.000000,0.000000,0.0,5.531129,0.0,120.62,11.814360,9.589074,0.0,6.544756,6.214601,0.000000,0.000000,5.425791,0.000000,10.106655,11.373799,0.000000,0.000000,23.224253,2.093981,9.644242,3.490747,0.000000,0.628767,-0.248657,0.0,0.250000,11.0,4.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,7.0,3.0,0.0,0.0,0.0,0.0,-2.6069,35.0232,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,2.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,10.521759,-0.752407,10.521759,0.278148,0.342148,138.086,136.070,138.01778,50.0,0.0,0.397445,-0.360476,0.397445,0.360476,1.600000,2.300000,2.800000,16.178377,10.340143,2.237557,-1.960002,1.815823,-2.392107,6.613325,-0.117193,3.037024,272.98218,7.560478,4.735487,4.735487,4.736382,2.352336,2.352336,1.502716,1.502716,0.864927,0.864927,0.443061,0.443061,-1.81,1.822382e+02,6.312100,2.200139,0.958376,55.178740,5.531129,6.214601,0.000000,0.00000,0.000000,17.649979,10.111326,4.794537,9.782271,0.000000,0.000000,0.000000,0.000000,0.000000,14.378941,23.864580,0.0,5.316789,4.992405,0.000000,0.000000,5.531129,0.0,0.0,5.316789,4.794537,0.0,0.00000,28.654446,4.794537,0.000000,0.000000,4.992405,0.0,5.531129,0.0,94.93,11.938294,9.589074,0.0,5.711685,0.000000,6.214601,0.000000,0.000000,5.316789,9.782271,5.531129,0.000000,0.000000,26.502214,1.813704,7.794129,-0.747685,-0.752407,0.890046,0.000000,0.0,0.000000,10.0,1.0,6.0,0.0,1.0,1.0,0.0,0.0,0.0,2.0,1.0,6.0,0.0,0.0,0.0,0.0,1.0,-1.0222,30.6571,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,1.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5,10.319305,-0.665463,10.319305,0.259074,0.266865,142.118,136.070,142.04907,54.0,0.0,0.344124,-0.368140,0.368140,0.344124,1.700000,2.300000,2.700000,16.155024,10.545581,2.005244,-1.907298,1.560501,-2.334459,6.237798,-0.122153,3.595897,193.43427,7.983128,5.072731,5.072731,4.663902,2.400904,2.400904,1.428686,1.428686,0.611839,0.611839,0.272312,0.272312,-1.68,1.254855e+02,8.320000,4.223754,4.478228,56.629143,16.581585,0.000000,0.000000,5.90718,0.000000,12.121780,9.589074,0.000000,4.789866,0.000000,0.000000,0.000000,0.000000,6.544756,14.378941,18.028960,0.0,5.316789,5.733667,0.000000,6.544756,5.531129,0.0,0.0,11.050456,0.000000,0.0,0.00000,29.363583,9.589074,0.000000,0.000000,0.000000,0.0,5.531129,0.0,108.59,11.814360,9.589074,0.0,6.544756,6.214601,0.000000,0.000000,0.000000,0.000000,15.840322,5.531129,0.000000,0.000000,22.752207,2.060231,12.470580,-1.318528,0.000000,0.627917,-0.259074,0.0,0.250000,10.0,3.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,6.0,3.0,0.0,0.0,0.0,0.0,-2.1115,31.8875,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,2.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,11.230461,-0.976244,11.230461,0.034298,0.241838,264.285,248.157,264.12225,102.0,0.0,0.361968,-0.386482,0.386482,0.361968,1.526316,2.263158,2.842105,16.297243,9.997065,2.231956,-2.195227,2.116195,-2.308720,6.463789,-0.112442,2.696947,463.59494,14.250712,10.690392,10.690392,9.116922,6.043024,6.043024,4.190793,4.190793,2.744441,2.744441,1.630926,1.630926,-2.11,1.610943e+04,14.949206,7.352275,4.239814,110.331300,10.637656,0.000000,0.000000,0.00000,5.783245,5.711685,9.803450,0.000000,4.789866,4.907065,19.420578,18.069946,12.620776,17.934608,14.690930,11.494930,0.0,5.008913,5.285885,25.869347,13.089513,34.239360,0.0,0.0,0.000000,0.000000,0.0,0.00000,45.593716,4.794537,4.907065,19.765380,29.087050,0.0,5.531129,0.0,106.37,11.887212,14.808130,0.0,12.256441,12.117861,12.841643,23.236973,0.000000,6.923737,10.075751,5.531129,0.000000,0.000000,24.681366,14.037472,8.890943,-0.435369,0.000000,4.670909,2.488013,0.0,0.500000,19.0,1.0,7.0,1.0,0.0,1.0,0.0,0.0,0.0,4.0,1.0,7.0,7.0,0.0,0.0,0.0,1.0,0.8669,69.1392,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,10.390084,-1.274317,10.390084,0.458148,0.225216,173.128,166.072,173.04366,66.0,0.0,0.413194,-0.479990,0.479990,0.413194,1.750000,2.333333,2.750000,16.534994,10.340294,2.137948,-2.029599,1.811069,-2.354436,6.201403,-0.144488,3.754635,232.84782,9.560478,6.005543,6.005543,5.574586,2.901785,2.901785,1.819340,1.819340,0.885492,0.885492,0.327609,0.327609,-1.72,3.324086e+02,10.280000,5.000236,4.152473,67.352000,21.108187,12.648723,0.000000,0.00000,0.000000,18.153212,4.794537,4.794537,4.789866,0.000000,0.000000,0.000000,0.000000,0.000000,24.222330,18.153212,0.0,0.000000,5.733667,6.041841,6.606882,5.531129,0.0,0.0,5.733667,0.000000,0.0,0.00000,40.698326,14.325937,0.000000,0.000000,0.000000,0.0,5.531129,0.0,126.02,24.587334,9.589074,0.0,0.000000,6.214601,0.000000,0.000000,0.000000,0.000000,9.526730,16.371325,4.251435,0.000000,22.831064,8.225461,12.809296,-2.224132,-1.262923,0.494614,-0.458148,0.0,0.400000,12.0,3.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,2.0,7.0,4.0,0.0,0.0,0.0,0.0,-1.7579,36.2536,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,1.0,0.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,11.336743,-0.992507,11.336743,0.008983,0.239740,236.231,224.135,236.09094,90.0,0.0,0.361616,-0.386485,0.386485,0.361616,1.588235,2.294118,2.764706,16.297205,9.998394,2.226336,-2.182315,2.109584,-2.300431,6.463777,-0.112528,2.754797,434.83197,12.836499,9.276179,9.276179,8.116922,5.043024,5.043024,3.429861,3.429861,2.340558,2.340558,1.345804,1.345804,-2.11,5.978220e+03,12.957159,5.833625,3.169685,97.601420,10.637656,0.000000,0.000000,0.00000,5.783245,5.711685,9.803450,0.000000,4.789866,4.907065,0.000000,24.648882,12.620776,17.934608,14.690930,11.494930,0.0,5.008913,5.285885,13.027703,13.089513,34.239360,0.0,0.0,0.000000,0.000000,0.0,0.00000,45.593716,4.794537,4.907065,6.923737,29.087050,0.0,5.531129,0.0,106.37,11.887212,14.808130,0.0,12.256441,12.117861,5.008913,18.228060,6.923737,0.000000,10.075751,5.531129,0.000000,0.000000,24.452793,13.621839,8.723254,-0.494296,0.000000,2.927768,2.101975,0.0,0.400000,17.0,1.0,7.0,1.0,0.0,1.0,0.0,0.0,0.0,4.0,1.0,7.0,5.0,0.0,0.0,0.0,1.0,0.0867,59.9052,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,12.729807,-1.064645,12.729807,0.073677,0.649284,406.906,379.690,406.15470,152.0,0.0,0.330629,-0.461571,0.461571,0.330629,1.178572,1.857143,2.500000,35.495705,9.488300,2.674517,-2.567600,2.669241,-2.582841,6.321759,-0.185329,1.790032,828.78375,20.482763,16.841492,17.597420,13.049002,10.022935,10.400899,9.359794,9.766993,8.145107,8.474695,6.764183,7.180077,-1.62,1.615358e+06,19.685862,6.186668,2.408853,170.015430,9.473726,6.606882,11.384295,0.00000,0.000000,11.938611,9.589074,4.794537,0.000000,0.000000,31.524435,55.933846,28.862024,0.000000,23.857338,29.322796,0.0,0.000000,28.583698,58.979286,6.606882,22.757431,0.0,0.0,0.000000,0.000000,0.0,11.60094,29.929789,23.857338,28.583698,53.378235,22.757431,0.0,0.000000,0.0,69.67,16.985346,14.383612,0.0,34.921257,18.059990,24.835570,19.923494,0.000000,0.000000,19.923494,21.074665,11.153576,6.651516,36.388664,0.608760,-0.950970,-0.220913,0.000000,6.601639,7.462172,0.0,0.681818,28.0,0.0,5.0,3.0,1.0,4.0,0.0,0.0,0.0,5.0,0.0,6.0,2.0,2.0,0.0,2.0,4.0,3.9456,103.3080,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
out.head(20)
# Y column - 1 -> mutagenic drug, 0 -> non-mutagenic drug

        ids                                             smiles  Y
0    Drug 0  O=[N+]([O-])c1ccc2ccc3ccc([N+](=O)[O-])c4c5ccc...  1
1    Drug 1       O=[N+]([O-])c1c2c(c3ccc4cccc5ccc1c3c45)CCCC2  1
2    Drug 2  O=c1c2ccccc2c(=O)c2c1ccc1c2[nH]c2c3c(=O)c4cccc...  0
3    Drug 3                          [N-]=[N+]=CC(=O)NCC(=O)NN  1
4    Drug 4                          [N-]=[N+]=C1C=NC(=O)NC1=O  1
5    Drug 5                           [N-]=[N+]=CC(=O)NCC(N)=O  1
6    Drug 6          CCCCN(CC(O)C1=CC(=[N+]=[N-])C(=O)C=C1)N=O  1
7    Drug 7                       [N-]=[N+]=CC(=O)OCC(N)C(=O)O  1
8    Drug 8            CCN(CC(O)C1=CC(=O)C(=[N+]=[N-])C=C1)N=O  1
9    Drug 9  CC(=O)OC1(C(C)=O)CCC2C3C=C(Cl)C4=CC(=O)OCC4(C)...  0
10  Drug 10                                    Nc1nc(N)nc(N)n1  0
11  Drug 11      Cc1ccc(N=Nc2c(O)ccc3ccccc23)c([N+](=O)[O-])c1  1
12  Drug 12                          CC(C)CC(=O)Nc1snc2ccccc12  0
13  Drug 13                           Cc1cccc([N+](=O)[O-])c1C  1
14  Drug 14   C#CC1(OC(=O)CCCCCC)CCC2C3CCC4=CC(=O)CCC4C3CCC21C  0
15  Drug 15                                    CCC[N+](=O)[O-]  0
16  Drug 16                 O=C(O)c1cc([N+](=O)[O-])cc2cccnc12  1
17  Drug 17                OC1C=Cc2c(ccc3c(Br)c4ccccc4cc23)C1O  1
18  Drug 18                            NC(=O)Nc1nc2ccccc2[nH]1  1
19  Drug 19                           C[C@@H](O)CCC(=O)c1ccoc1  0